version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - db
    environment:
      DATABASE_HOST: db

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - '5432:5432'
