version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'mwarchol33@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'pgadminPassword'
    ports:
      - '5050:80'
    depends_on:
      - db
